apiVersion: v1
kind: Service
metadata:
  name: {{ include "pensato.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "pensato.name" . }}
    helm.sh/chart: {{ include "pensato.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
    - port: 22
      targetPort: sftp
      name: sftp
  selector:
    app.kubernetes.io/name: {{ include "pensato.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
status:
  loadBalancer: {}
